### ISSUE TITLE
Error: Network connection lost.

### ISSUE THREAD

**Issue by pierre818181** [cloudflare/serverless-registry#69]
I get this error once all the PATCH requests are done and the finishUpload is called. I can consistently reproduce this at the same stage during push.

Is this something to do with my Cloudflare level?

Stack:

```
error error Error: Network connection lost.: undefined: Error: Network connection lost.
    at async R2Registry.finishUpload (index.js:6416:7)
    at async index.js:5246:22
    at async fetch (index.js:13:27)
    at async Object.fetch (index.js:13:27)
    at async Object.fetch (index.js:6482:19)
```

**Comment by pierre818181** [comment]
Here is the state that is being uploaded:

```
state {
  uploadId: 'ABaNiYJA5zfJ4O9-dFMmijzOofxK06sc0qSiGmb2fJW8c3PLYJA8hutltpkLleqoz06bwq6d22q5nqr1eNK4FHhTfFiDkihte9nlElq0eWy5dUOOYVMUechjSzy2NKLE4DFqD-oc7nSmpcepCZ6hje9pp2Fj_wsw7unKjTnjETBXpENyZYTld7CW2pyjHzaOSTn8c3dnVK0xMqcj4p5BwCFThG_B2JFAv_68K8rkbMArL8D-ebOAI95ntVCIclkVwfByuU5KOmfChhsN7vyBLZW7SOLm9h0PKJd-m2dkpocjf0rsaLFvmTQ_BC0iF23twsq29ahvXWjoNy1cypBUN_A',
  parts: [
    { partNumber: 1, etag: 'd7a7e0beb35179c005f4897370b9ff1b' },
    { partNumber: 2, etag: '7f95cc8de77b61af8ee23ce012dfe27b' },
    { partNumber: 3, etag: '8fe70765897f921cd7a221228910a0b6' },
    { partNumber: 4, etag: '56e242b479ad104c5e3bf900e1f336bf' },
    { partNumber: 5, etag: '5d869bd1d18b5e4953ce28bb01f9cbed' },
    { partNumber: 6, etag: '39c6b8f58cc0a526c1a29d779ecea34b' },
    { partNumber: 7, etag: 'b2ee0bfcdb4d0d7fedc311f2740a5e6d' },
    { partNumber: 8, etag: '7347109d0af22394af7f79c594e3250f' },
    { partNumber: 9, etag: '744b161f27464760382b9423b1afa9a2' },
    { partNumber: 10, etag: '252d2000f5c61985ea4948fd481bd4c4' },
    { partNumber: 11, etag: '9f6b1e2c92ac70f46c5ea8978fab6fbe' },
    { partNumber: 12, etag: 'b67156d0930487365126d8652123337f' },
    { partNumber: 13, etag: 'ebd767ff00d516884283891324c86572' },
    { partNumber: 14, etag: '65af7825047ef42d34f484c4e4db2bac' },
    { partNumber: 15, etag: '8e89ebcff6164c79555bd7786fa9b2b6' },
    { partNumber: 16, etag: 'b0172803bfa48729bf477b66261d2609' },
    { partNumber: 17, etag: '3e0f3bcbd8dba655098e26ea8d90c807' },
    { partNumber: 18, etag: 'de075fc38db3499b178752e6d24db687' },
    { partNumber: 19, etag: '677eafba0640adb52911522bbfdc5899' },
    { partNumber: 20, etag: '2b3d824ff344b2431afa324b80ec9d8a' },
    { partNumber: 21, etag: '38b13e28befe94a8c5e157c2c0f1cce0' },
    { partNumber: 22, etag: '7f8e0a2554ccec87f1dcf00fed1d3e81' },
    { partNumber: 23, etag: '2d6be07abeb39dfb61032f9edd3b7f69' },
    { partNumber: 24, etag: '6e00e5a8e7b4c77d6c16d0bbdef597fb' },
    { partNumber: 25, etag: '13756d3752657deb6d788791088d7ca2' },
    { partNumber: 26, etag: 'e5cee67f23682f08831dd60732b1391f' },
    { partNumber: 27, etag: 'e790cf5469209867c50ba09a141a1fff' },
    { partNumber: 28, etag: 'e940203c572bb2276533c42db6f176ac' },
    { partNumber: 29, etag: 'd4da68e9d432ae7098ce3e500c317b00' },
    { partNumber: 30, etag: '451ed08bbb90efdcdd73357a959c711d' },
    { partNumber: 31, etag: '8f266e8e46ddf17731a6f915bb6e2ec3' },
    { partNumber: 32, etag: 'f7db7df4fe5fdb9c104d165c7d90b859' },
    { partNumber: 33, etag: '996e188d1b1c16bfd91b8a50e0a94d1d' },
    { partNumber: 34, etag: '7454dfc347f179c4f09df9fc3ca3c52b' },
    { partNumber: 35, etag: '1c8228b25a016879c7e49244e788d3e3' },
    { partNumber: 36, etag: '695c86a141f7f37170062c1e60866921' },
    { partNumber: 37, etag: 'd533aeeebfdd2484a72128c73e33dd8a' },
    { partNumber: 38, etag: '642bdc3c445f9f96ea96e2f462eab329' },
    { partNumber: 39, etag: 'e671818189aa90bd4c8906471dbcc08c' },
    { partNumber: 40, etag: 'e8e5f8a13c8256d1579428b7bbe2e339' },
    { partNumber: 41, etag: '8406466ea286ad266366d0686212c508' },
    { partNumber: 42, etag: '76d0a65fa6e3c4018ce736bbed7c6084' },
    { partNumber: 43, etag: 'e30599c04a8d381e0e356912c8d2ebef' },
    { partNumber: 44, etag: 'fa4c088714a50a9d1620057b5339cfb1' },
    { partNumber: 45, etag: '34542670c53440335b0ece44339b69b4' },
    { partNumber: 46, etag: 'c71d39695353d34293afcf8772bb2f4f' },
    { partNumber: 47, etag: 'df79b2b15cf498495c1bc68732bab81e' },
    { partNumber: 48, etag: '2e692099e22b1fe3ed6dae8ded916c71' },
    { partNumber: 49, etag: 'f3fa88eb4d4e1fccc28d4de096ee010e' },
    { partNumber: 50, etag: 'b620435704192124f848b710e2bba46b' },
    { partNumber: 51, etag: 'df2f8ba8d44195af8362934fcf188ef0' },
    { partNumber: 52, etag: 'a5f8124350929cb39f8bf8f263c6402a' },
    { partNumber: 53, etag: '2836dfabbfbccb6be46b7178ccd8e45f' },
    { partNumber: 54, etag: 'fb82e3b690c2e54e6d987d84920422eb' },
    { partNumber: 55, etag: '745b42bac99dc3a90a9d4063b5240e0a' },
    { partNumber: 56, etag: '198b4eea737846276a088b332c8c77d3' },
    { partNumber: 57, etag: '6687c16408b563c7247301d30104cf98' },
    { partNumber: 58, etag: '613e76e64a682a22cdc86508cc705e58' },
    { partNumber: 59, etag: 'f0c2d283e14792296eba413e47e1b03c' },
    { partNumber: 60, etag: '8075d904142f3181f88018360b4023fd' },
    { partNumber: 61, etag: '344c8340dc00a54974c41a943a25e17c' },
    { partNumber: 62, etag: '14fd500437f9bac718f07c7c84aacdfa' }
  ],
  registryUploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a',
  byteRange: 6135021548,
  name: 'pierre818181-kaniko-threat-test-01d26',
  chunks: [
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk',
      size: 100000000,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a'
    },
    {
      type: 'multi-part-chunk-no-same-size',
      size: 35021548,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a',
      r2Path: '4926fa35-7d20-41d3-b91c-7075d3d3462a-helper'
    }
  ],
  exp: 1729550841,
  iat: 1729542852
} 
```

**Comment by pierre818181** [comment]
I have a strong feeling this is responsible for the problem:

```
{
      type: 'multi-part-chunk-no-same-size',
      size: 35021548,
      uploadId: '4926fa35-7d20-41d3-b91c-7075d3d3462a',
      r2Path: '4926fa35-7d20-41d3-b91c-7075d3d3462a-helper'
    }
    ```

**Comment by gabivlj** [comment]
Hello! Thank you for the issue. I am curious to see how are you pushing layers? Docker push? Whats your container image like?

**Comment by gabivlj** [comment]
I found out the issue, the layer you are trying to push is more than 5gib, which goes against the R2 limits as we try to do a copy to change the path of the object. I will try to have some fix for this.

**Comment by pierre818181** [comment]
Sure @gabivlj

**Comment by pierre818181** [comment]
> Hello! Thank you for the issue. I am curious to see how are you pushing layers? Docker push? Whats your container image like?

we are using the index.ts inside push folder to push

**Comment by pierre818181** [comment]
@gabivlj any chance you have been able to look into this?

**Comment by gabivlj** [comment]
Hi @pierre818181, I looked into this, I think I know a possible solution, just haven't gotten to implementing yet! Sorry for the issue, will get to this when I get some time.

**Comment by gabivlj** [comment]
Hi @pierre818181, can you check if https://github.com/cloudflare/serverless-registry/pull/78 works for you?

**Comment by pierre818181** [comment]
Hi @gabivlj I just tried and see the same issue on the cloudflare logs. Here are the upload logs:

```
2024-11-25 14:39:33
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 7434927308 upload bytes left.
2024-11-25 14:39:45
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 7334927308 upload bytes left.
2024-11-25 14:39:53
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 7234927308 upload bytes left.
2024-11-25 14:40:05
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 7134927308 upload bytes left.
2024-11-25 14:40:17
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 7034927308 upload bytes left.
2024-11-25 14:40:31
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 6934927308 upload bytes left.
2024-11-25 14:40:42
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 6834927308 upload bytes left.
2024-11-25 14:40:51
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 6734927308 upload bytes left.
2024-11-25 14:41:02
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 6634927308 upload bytes left.
2024-11-25 14:41:15
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 6534927308 upload bytes left.
2024-11-25 14:41:25
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 6434927308 upload bytes left.
2024-11-25 14:41:37
[INFO]
sha256:09efbcfccf416036d57e24719b0884df9b5c1d381b87d53b82757abb26252899: 6334927308 upload bytes left.
```

Here are the cloudflare logs:

```
"Uploading chunk: error Error: Network connection lost.: undefined: Error: Network connection lost. at async appendStreamKnownLength (index.js:6383:22) at async R2Registry.uploadChunk (index.js:6452:17) at async index.js:5586:22 at async fetch (index.js:13:27) at async Object.fetch (index.js:13:27) at async Object.fetch (index.js:6610:19)",
```

Previously it used to fail once all the bytes have been uploaded. Now its failing much earlier - not sure what the reason is.
If it helps, can you fork this repo (https://github.com/runpod-workers/worker-vllm) and try pushing it to your CF repository? It produces one 8.5 G layer

**Comment by gabivlj** [comment]
Hello @pierre818181, in that same branch I added a WIP commit that I tested with retry logic. Is this transient issue still occurring after that?

Where is this image being pushed from?

**Comment by gabivlj** [comment]
I just noticed that the Worker might throw a Workers CPU exception when calculating the digest; I will try another approach later.

**Comment by gabivlj** [comment]
Hello. I added another commit that should allow you to circumvent this issue (sorry for all the debugging in this issue!)

**Comment by Dramelac** [comment]
Hello @gabivlj 
I've reproduce the same error as @pierre818181 on the `main` branch and yes I can confirm you, the fix on the branch `gv/69` works (tested with a 10Gb~ layer) !
When can we hope for a merge to main ?
